### ISSUE TITLE
Issue with security-rules in security-lists module

### ISSUE THREAD

**Issue by octopus20** [Binsabbar/oracle-cloud-terraform#3]
**Describe the bug**
module: security-list
version: 1.0
oci version: 4.20.0
description: When adding rules under security_lists (egress_rules & ingress_rules), terraform will throw an error (The given value is not suitable for child module variable "security_lists") .. this happened because of the defined type of "optionals" variable in variables.tf file. I managed to fix this by changing the type from "any" to "map(any)" and using empty brackets as a value for optionals (optionals= {}) 

**To Reproduce**
1. User security-lists module
2. Create security lists and add security rules (ingress_rules & egress_rules)
3. terraform apply 

```
The given value is not suitable for child module variable "security_lists"
defined at
.terraform/modules/security_lists/modules/security-list/variables.tf:4,1-26:
object is required.
```

**Comment by Binsabbar** [comment]
@octopus20 can you show full example of module usage please so I can reproduce it?

**Comment by octopus20** [comment]
Hello @Binsabbar,  to reproduce the bug, try to add below to the module and run terraform plan or apply. 

```security_lists = {
    "test_rules" = {
      ingress_rules = {
        "lb8002" = {
          ports     = { min : 8002, max : 8002 }
          source    = "0.0.0.0/0"
          protocol  = local.protocols.tcp
          optionals = {} // the bug will happen because of the value of this line ( I tried to leave it empty + empty "" + empty {}) all are invalid values. 
        }
      }
      egress_rules = {
      }
    }
