### ISSUE TITLE
instances metadata missing user_data

### ISSUE THREAD

**Issue by BYAT** [Binsabbar/oracle-cloud-terraform#39]
**Describe the bug**
module: instances
version: 
oci version: 4.79.0
description: Trying to use metadata to configure Cloud-Init, found the Cloud-Init script wasnt run on instance as expected. Metadata  attribute suppose to have `user_data` attribute in order to run Cloud-Init custom scripts

**Expected behavior**
update the instances module to include `user_data` attribute

**Comment by Binsabbar** [comment]
I created v.2.3.0-dev branch now with a fix that does not introduce breaking changes. I will merge it in the upcoming days after some testing. It is added under `optionals` block.

In v3 I will probably move both authorization_keys and user_metadata under one input block
